# Generated by Django 5.0.6 on 2025-11-23 19:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_badge_domain_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airecommendation',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('collab_request', 'Collaboration Request'), ('collab_accepted', 'Collaboration Accepted'), ('collab_declined', 'Collaboration Declined'), ('comment', 'New Comment'), ('like', 'Project Liked'), ('follow', 'New Follower'), ('message', 'New Message')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('related_url', models.URLField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.project')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
